[env:test-usb]
platform = atmelavr
board = ATmega328P
board_build.f_cpu = 16000000L
framework = arduino
lib_deps = 
	bblanchon/ArduinoJson@^6.20.0
	C:\Users\nicol\Documents\Arduino\libraries\SitronLabs_Diodes_PI3USB9281C_Arduino_Library
	C:\Users\nicol\Documents\Arduino\libraries\SitronLabs_Generic_EEPROM_Arduino_Library
	C:\Users\nicol\Documents\Arduino\libraries\SitronLabs_Onsemi_FSUSB43_Arduino_Library
	C:\Users\nicol\Documents\Arduino\libraries\SitronLabs_Onsemi_FUSB302_Arduino_Library
lib_extra_dirs = C:\Users\nicol\Documents\Arduino\libraries
monitor_speed = 115200

[env:slto00001-r4j]
platform = ststm32
board = nucleo_f072rb
board_build.mcu = stm32f072cbt6
framework = arduino
build_flags =
	-D R4J
	-D PIO_FRAMEWORK_ARDUINO_ENABLE_CDC
	-D PIO_FRAMEWORK_ARDUINO_NANOLIB_FLOAT_PRINTF
	-D PIO_FRAMEWORK_ARDUINO_USB_FULLMODE
	-Wall
	-Wextra
lib_deps = 
	bblanchon/ArduinoJson@^6.20.0
	robtillaart/RunningMedian@^0.3.8
	tobiasebsen/KalmanFilter@^1.0.0
	C:\Users\nicol\Documents\Arduino\libraries\SitronLabs_Diodes_PI3USB9281C_Arduino_Library
	C:\Users\nicol\Documents\Arduino\libraries\SitronLabs_Generic_EEPROM_Arduino_Library
	C:\Users\nicol\Documents\Arduino\libraries\SitronLabs_Memsic_MC34X9_Arduino_Library
	C:\Users\nicol\Documents\Arduino\libraries\SitronLabs_Onsemi_FSUSB43_Arduino_Library
	C:\Users\nicol\Documents\Arduino\libraries\SitronLabs_Onsemi_FUSB302_Arduino_Library
	C:\Users\nicol\Documents\Arduino\libraries\SitronLabs_Solomon_SSD1306_Arduino_Library
lib_extra_dirs = C:\Users\nicol\Documents\Arduino\libraries
upload_protocol = stlink
debug_tool = stlink
monitor_speed = 115200

[env:slto00001-r8a]
platform = https://github.com/maxgerhardt/platform-raspberrypi.git
board = pico
board_build.core = earlephilhower
board_build.filesystem_size = 0.5m
framework = arduino
build_flags =
	-D R8A
	-Wall
	-Wextra
lib_deps = 
	bblanchon/ArduinoJson@^6.20.0
	robtillaart/RunningMedian@^0.3.8
	tobiasebsen/KalmanFilter@^1.0.0
	C:\Users\nicol\Documents\Arduino\libraries\SitronLabs_Diodes_PI3USB9281C_Arduino_Library
	C:\Users\nicol\Documents\Arduino\libraries\SitronLabs_Generic_EEPROM_Arduino_Library
	C:\Users\nicol\Documents\Arduino\libraries\SitronLabs_Memsic_MC34X9_Arduino_Library
	C:\Users\nicol\Documents\Arduino\libraries\SitronLabs_Onsemi_FSUSB43_Arduino_Library
	C:\Users\nicol\Documents\Arduino\libraries\SitronLabs_Onsemi_FUSB302_Arduino_Library
	C:\Users\nicol\Documents\Arduino\libraries\SitronLabs_Solomon_SSD1306_Arduino_Library
lib_extra_dirs = C:\Users\nicol\Documents\Arduino\libraries
monitor_speed = 115200
